### ISSUE TITLE
关于HITS@1非常小的问题

### ISSUE THREAD

**Issue by bbbbbbxy** [Sphinx1126/RelaGraph#2]
有没有同学也遇到一样的问题啊，就是文章在这三个数据集上面结果和文章的差不多，但是在fb15k-237，wn18rr上面进行运行的时候，不管是Rela+TripleRE还是TripleRE，HITS@10指标都很好，但是MR和hits@1都非常差，只有零点几的样子，请问是我哪里设置错误了吗，但是理论上来说，就算是rela不适合FB15K这样的数据集上面，那我不用RELA只要tripleRE应该也不会hits@1这么小啊。这是为什么啊，有没有大佬解答一下

**Comment by Sphinx1126** [comment]
是否更改了相应的超参数？dim size、epoch、batch size等参数需要进行相应的修改，可以参考StarGraph那个项目的设置。我们之前在fb15k237上进行过实验，MRR应该在0.36左右。

**Comment by bbbbbbxy** [comment]
好的，我再去尝试一下！谢谢你的解答！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月17日 11:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Sphinx1126/RelaGraph] ***@***.***非常小的问题 (Issue #2) |

是否更改了相应的超参数？dim size、epoch、batch size等参数需要进行相应的修改，可以参考StarGraph那个项目的设置。我们之前在fb15k237上进行过实验，MRR应该在0.36左右。
